name: Build Test
on:
  push:
    branches: [ "*" ]
    paths-ignore:
        - "**/**.md"
        - "CMakePresets.json"
        - ".*"
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]
        compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            compiler: cl
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
          - os: ubuntu-latest
            compiler: cl
    steps:
    - uses: actions/checkout@v4
    - name: Prepare Vulkan
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      with:
       vulkan-query-version: latest
       vulkan-components: Vulkan-Headers, Vulkan-Loader
    - name: Install Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev
    - name: Configure
      run: >
        cmake -B build -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S ${{ github.workspace }}
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel 9
