name: Build Test
on:
  push:
    branches: [ "*" ]
    paths-ignore:
        - "**/**.md"
        - "CMakePresets.json"
        - ".*"
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]
        compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            compiler: cl
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
          - os: ubuntu-latest
            compiler: cl
    steps:
    - uses: actions/checkout@v4
    - name: Prepare Vulkan
      uses: jakoch/install-vulkan-sdk-action@v1
      with:
          optional_components: com.lunarg.vulkan.vma
          install_runtime: true
          cache: true
          stripdown: true
    - name: Install Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev
    - name: PWD
      run: |
        pwd
    - name: Configure
      run: cmake -B ${{ github.workspace }}/buildDirectory -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S ${{ github.workspace }}
    - name: Build
      run: cmake --build ${{ github.workspace }}/buildDirectory --config ${{ matrix.build_type }} --parallel 9
